<?php

namespace Database\Seeders;

use App\Models\Screen;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use  App\Services\LetterConverter;

class ScreenSeederIntermediateKU extends Seeder
{

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $converter = new LetterConverter();
        $screens = [

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١', 'content_type' => 'sentences', 'content' => 'لەگەڵ وەک من ئەو ئەوان بن لە بوون  یەک هەیە ئەم لە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ٢', 'content_type' => 'sentences', 'content' => 'ئەو لە بۆ و لە ئەوە تۆ کە ئەو بوو بۆ لەسەر',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ٣', 'content_type' => 'sentences', 'content' => 'هەریەکێک ئەو کە کاتەکانیان ئەگەر دەبێت ڕێگە دەربارەی',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ٤', 'content_type' => 'sentences', 'content' => 'کەی بوون هەموو تر تۆ تا بەکارهێنانی ووشە چۆن وتی یەک',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ٥', 'content_type' => 'sentences', 'content' => 'یان هەبوو لەلایەن گەرم بەڵام هەندێک چی لەوێ دەتوانین دەرەوە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ٦', 'content_type' => 'sentences', 'content' => 'زۆرێک پاشان ئەوان دەنووسن وەک بۆیە ئەمانە ئەو درێژ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 7, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ٧', 'content_type' => 'sentences', 'content' => 'ڕۆژ بکەن شت ببینن ئەو دوو هەیە سەیر زیاتر دەتوانێت بچێت',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 8, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ٨', 'content_type' => 'sentences', 'content' => 'وەرە کرد دەنگی من هیچ زۆربەی ژمارە کێ لەسەر دەزانن',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 9, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ٩', 'content_type' => 'sentences', 'content' => 'ئاو لە بانگ یەکەم کەسەکان ڕەنگ دابەزین لایەن بووە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 10, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١٠', 'content_type' => 'sentences', 'content' => 'ئێستا دۆزینەوەی هەر کارێکی نوێ بەشێک وەربگرە بەدەستبهێنە شوێن دروستکراوە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 11, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١١', 'content_type' => 'sentences', 'content' => 'بژین لە کوێ دوای دواوە کەمێک تەنها دەوری پیاو ساڵ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 12, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١٢', 'content_type' => 'sentences', 'content' => 'هات نیشان هەموو باش من بدە ئێمە لە ژێر ناوی زۆر',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 13, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١٣', 'content_type' => 'sentences', 'content' => 'لە ڕێگەی تەنها فۆرم زۆر گەورە بیربکەنەوە بڵێن یارمەتی نزم',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 14, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١٤', 'content_type' => 'sentences', 'content' => 'خەڵك پێش سوڕانەوە هۆکار هەمان دیار جیاواز جوڵە ڕاست',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 15, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١٥', 'content_type' => 'sentences', 'content' => 'کوڕ پیر زۆر دەکات بڵێ کچ ژن دەوێت هەوا',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 16, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١٦', 'content_type' => 'sentences', 'content' => 'باشە هەروەها یاری بچووک کۆتایی داناوە ماڵەوە خوێندنەوە دەست مووچە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 17, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١٧', 'content_type' => 'sentences', 'content' => 'گەورە بچووک زیاد تەنانەت زەوی لێرە دەبێت گەورە بەرز چەپ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 18, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١٨', 'content_type' => 'sentences', 'content' => 'پێویستە وێنەی ماڵ هەوڵمان بدە دووبارە ئاژەڵ خاڵ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 19, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان - ١٩', 'content_type' => 'sentences', 'content' => 'دایک جیهان نزیک دروستکردن فرۆشت زەوی باوک سەر',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 20, 'exercise_id' => 17, 'title' => 'ووشە زۆر باوەکان', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 18, 'title' => 'ڕیزی ناوەڕاست - ١', 'content_type' => 'sentences', 'content' => 'کێشەی درێغی ساڵی کێوماڵکردنی دۆلار هەفتە هاژین کرد بڵاودەكاتەوە بڵند دەستگیرکران دابەشکردنی بەغداد گلوکۆز سەمفۆنیا ئاسایشی قه‌ده‌غه‌كرا هۆشداری شمشاڵ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 18, 'title' => 'ڕیزی ناوەڕاست - ٢', 'content_type' => 'sentences', 'content' => 'دووکان هەفتە ئاشکراکرد دارایی کرد ساماڵ مەغریبییەک داغستان دۆلار سكاڵا فرۆشگا کورد دەستگیرکران ساڵ هۆشداری فیلم پشکی غاز کێشەی',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 18, 'title' => 'ڕیزی ناوەڕاست - ٣', 'content_type' => 'sentences', 'content' => 'قۆناغ شلە ساڵی کارکردنەوەی سەردانی هەفتەی هەڵۆ کەشناسی بڵند ئاسایشی سەمفۆنیا کاهوو گلوکۆز کەرکووک دەستپێدەكات سلیکۆن فیدڕاڵی درێغی سەنگین دادگای منداڵ دەرگا',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 18, 'title' => 'ڕیزی ناوەڕاست - ٤', 'content_type' => 'sentences', 'content' => 'دارایی دادگای بڵاودەكاتەوە کرد کورد گلوکۆز فرۆشگایەکی سەنگین مەغریبییەک کارکردنەوەی دەستپێدەكات پشکی هەفتە هاژین شلیک قه‌ده‌غه‌كرا کاهوو ژنێک',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 18, 'title' => 'ڕیزی ناوەڕاست - ٥', 'content_type' => 'sentences', 'content' => 'غاز ساڵی کرد سەمفۆنیا هەڵبژاردنی سەنگین هەفتە فرۆشگایەکی کێوماڵکردنی رۆژهەڵاتی کەساس قه‌ده‌غه‌كرا بەغداد ئاشکراکرد شلە ژنێک سەردانی گلوکۆز کەشناسی کلتور هەڵۆ دەرفەت سكاڵا شنگال ساماڵ دۆلار دەستپێدەكات کیبۆرد کورد بڵاودەكاتەوە دهۆک فرۆشگا کێشە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 18, 'title' => 'ڕیزی ناوەڕاست - ٦', 'content_type' => 'sentences', 'content' => 'شەمشەمەکوێرە کارکردنەوەی هاژین هەنگوین منداڵ دادگای ساڵ هۆشداری دارایی دەستگیرکران سلیکۆن درێغی دەرگا فیدڕاڵی مەغریبییەک شلیک شمشاڵ کەرکووک قۆناغ ئاسایشی دژی بڵند هەفتەی داغستان دابەشکردنی کاهوو فیلم پشکی',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 7, 'exercise_id' => 18, 'title' => 'ڕیزی ناوەڕاست - ٧', 'content_type' => 'sentences', 'content' => 'دژی رۆژهەڵاتی دەستپێدەكات دەستگیرکران دارایی فیدڕاڵی سەمفۆنیا سەردانی هەنگوین فرۆشگا قه‌ده‌غه‌كرا ساڵ فرۆشگایەکی دادگای کێوماڵکردنی هەفتە دووکان کرد کەشناسی قۆناغ شلە دۆلار شلیک داغستان درێغی هەڵۆ شمشاڵ دەرگا فیلم کاهوو ئاسایشی کلتور',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 8, 'exercise_id' => 18, 'title' => 'ڕیزی ناوەڕاست - ٨', 'content_type' => 'sentences', 'content' => 'شنگال بڵند سلیکۆن سكاڵا کورد کارکردنەوەی مەغریبییەک شەمشەمەکوێرە ساڵی کەساس دابەشکردنی هاژین کێشەی دەرفەت پشکی گلوکۆز دهۆک منداڵ بەغداد هۆشداری ساماڵ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 9, 'exercise_id' => 18, 'title' => 'ڕیزی ناوەڕاست - ٩', 'content_type' => 'sentences', 'content' => 'هەڵبژاردنی کەشناسی فیلم پشکی هەنگوین بڵاودەكاتەوە غاز کێوماڵکردنی کرد دەرفەت فرۆشگا فیدڕاڵی گلوکۆز کیبۆرد شنگال شمشاڵ داغستان دەستپێدەكات دووکان هەفتە درێغی رۆژهەڵاتی سكاڵا هەفتەی ئاشکراکرد کاهوو',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 10, 'exercise_id' => 18, 'title' => 'ڕیزی ناوەڕاست', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە - ١', 'content_type' => 'sentences', 'content' => 'یاپراخ ئۆکرانیا پاسکیل یارسان گواستنەوەی هەتاو قیڕەقیڕ پاشەکەوت پۆڕ مەعکەرۆنی ترێ قۆڕی تەماتە کتری وردەکاری قەرەوەیس ڕاستە یارمەتی کفتە قورئان پەڵپینە تەتەڵە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە - ٢', 'content_type' => 'sentences', 'content' => 'پیرۆزبایی ڕەش ئیتاڵیا عیبری ڕاستگۆ دەرەوەی تەماتە رابردوو عەمرە بەنزینجوتیاران پرۆگرامینگ ڕێنیسانس ووشە پۆرت شارەوانی قایمقام هەولێر کۆتر ئەمڕۆ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە - ٣', 'content_type' => 'sentences', 'content' => 'پاریس ئەنجومەنی توتڕک تەختە تەڕەتیزە پیاز ئەمبەروەری نەوت عەممان پسکیت پەتاتە عەمرە عه‌مباری قۆری ئۆتۆمبێلێک عەرەبانە ووریایی ئەوروپا پێنووس پیرۆز تەندروستی سەرقاپ تۆڕ وێبگەڕ پیانۆ مرۆڤ پەرەمێز',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە - ٤', 'content_type' => 'sentences', 'content' => 'دەرەوەی قورئان رابردوو عەمرە عەرەبانە ئۆکرانیا نەوت پۆڕ شارەوانی کتری پەتاتە ڕەش پیرۆز مەعکەرۆنی پسکیت ئەنجومەنی ئەمڕۆ پۆرت قەرەوەیس یاپراخ یارمەتی مرۆڤ پەرەمێز پرۆگرامینگ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە - ٥', 'content_type' => 'sentences', 'content' => 'هەتاو ئەمبەروەری ئەوروپا کۆتر عیبری ووشە وێبگەڕ قۆڕی یارسان قۆری پاشەکەوت تەندروستی ئیتاڵیا عەمرە تەختە تەتەڵە ووریایی عه‌مباری کفتە گواستنەوەی هەولێر ڕاستگۆ توتڕک پەڵپینە پیاز پاسکیل سەرقاپ ئۆتۆمبێلێک پاریس',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە - ٦', 'content_type' => 'sentences', 'content' => 'ئەنجومەنی پەتاتە توتڕک پیرۆز ڕەش ئەمبەروەری مەعکەرۆنی سەرقاپ تۆڕ ڕێنیسانس یاپراخ مرۆڤ قیڕەقیڕ هەتاو یارسان عه‌مباری بەنزینجوتیاران پاشەکەوت وردەکاری گواستنەوەی پاریس کفتە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 7, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە - ٧', 'content_type' => 'sentences', 'content' => 'ئەمڕۆ پسکیت پاسکیل ووریایی تەڕەتیزە عەمرە عیبری پیرۆز پیانۆ مەعکەرۆنی ئۆکرانیا ئۆتۆمبێلێک تۆڕ عەمرە کتری پەتاتە پاریس عه‌مباری پۆرت قۆڕی پیرۆزبایی تەختە پرۆگرامینگ تەماتە ئیتاڵیا',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 8, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە - ٨', 'content_type' => 'sentences', 'content' => 'ووشە پەرەمێز نەوت پیاز کۆتر ڕێنیسانس عەممان پێنووس رابردوو یارسان ئەمبەروەری گواستنەوەی پاشەکەوت تەندروستی یاپراخ ڕاستگۆ قۆری ڕەش ترێ توتڕک هەتاو هەولێر دەرەوەی کفتە عەرەبانە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 9, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە - ٩', 'content_type' => 'sentences', 'content' => 'قایمقام پیاز دەرەوەی پاسکیل تۆڕ تەماتە پرۆگرامینگ ئۆکرانیا تەندروستی نەوت وردەکاری عەمرە قەرەوەیس توتڕک پۆڕ ووشە ڕاستگۆ ئەوروپا هەتاو شارەوانی ئەمبەروەری ڕەش پیانۆ قیڕەقیڕ مرۆڤ یارمەتی گواستنەوەی',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 10, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە - ١٠', 'content_type' => 'sentences', 'content' => 'قیڕەقیڕ ووشە پیرۆز ئەوروپا ڕاستگۆ تەڕەتیزە ئەمڕۆ نەوت عەممان دەرەوەی یارسان کۆتر ئەنجومەنی عەمرە هەتاو قایمقام پاریس پاسکیل قۆری ئیتاڵیا ئۆتۆمبێلێک کفتە وێبگەڕ یارمەتی وردەکاری پاشەکەوت',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 11, 'exercise_id' => 19, 'title' => 'ڕیزی سەرەوە', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 20, 'title' => 'ڕیزی خوارەوە - ١', 'content_type' => 'sentences', 'content' => 'گۆڤار خۆڵ چەوت چیمەن رۆژنامەڤان چی نزا خێزان ناوچەکانمان بازیان زەوی جەمەلۆن مرۆڤایەتیی چەمچەماڵ ئالۆڤێرا خوێندنەوە باڵیۆزخانەکان چۆن زانست چەماوە زۆن سلێمانی',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 20, 'title' => 'ڕیزی خوارەوە - ٢', 'content_type' => 'sentences', 'content' => 'نزم نوێن مۆم ئەندازیار بەنزین تەنگپێهەڵچنین ڕۆژئاڤا نان باڵیۆزخانەکان زیندان زوڵم رۆژنامەڤان مرۆڤایەتیی ململانێ خوێندنەوە باخەوان خورمەڵە  خۆشگوزەرانی نزا چۆن زەوی نڤیشکان مامە ناوچەکانمان خوێ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 20, 'title' => 'ڕیزی خوارەوە - ٣', 'content_type' => 'sentences', 'content' => 'خێمە ئەندازیار باڵیۆزخانەکان زۆن بومەلەرزەزانی نیوزلەندا قەڵادزێ زیندان ناوازە زانا نیاز خزم بازیان زانکۆ زەنگین زستان کانزا ڕەواندز نزم نزا زوڵم میوزیک بەنزین چیمەن چەوت چەماوە ناوچەکانمان  تەنگپێهەڵچنین',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 20, 'title' => 'ڕیزی خوارەوە - ٤', 'content_type' => 'sentences', 'content' => 'ئالۆڤێرا خشت نەخۆشی خۆشه‌ویستی خوێندنەوە باخەوان خۆشگوزەرانی خێزان خۆڵ نانەواخانە  بومەلەرزەزانی نیوزلەندا قەڵادزێ زیندان ناوازە زانا نیاز خزم بازیان زانکۆ زەنگین زستان کانزا',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 20, 'title' => 'ڕیزی خوارەوە - ٥', 'content_type' => 'sentences', 'content' => 'نیاز ناشڤێل زوڵم زستان کانزا کەرنەڤاڵی باران بەگژداچوونەوە ڤایرۆس خۆڵ خورمەڵە تەنگپێهەڵچنین بازیان بەرگدروو زیندان چاک جامچی جەمەلۆن چەوت پێچەوانە مەنجەڵ بنەچە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 20, 'title' => 'ڕیزی خوارەوە - ٦', 'content_type' => 'sentences', 'content' => 'قەڵادزێ زانست بازیان نەخۆشی زۆن جەمەلۆن ناشڤێل نزم ئالۆڤێرا باڵیۆزخانەکان بەگژداچوونەوە ناوازە چاک مامۆستا خەمە ڤایکینگ بنەچە کانزا مامە چۆن جەلی زیندان نڤیشکان مرۆڤایەتیی نوێن بومەلەرزەزانی',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 7, 'exercise_id' => 20, 'title' => 'ڕیزی خوارەوە - ٧', 'content_type' => 'sentences', 'content' => 'میوزیک ناوچەکانمان بازیان جامچی بەرگدروو خۆشگوزەرانی زەنگین نڤیشکان باڵیۆزخانەکان زوڵم ئالۆڤێرا پێچەوانە چەوت باخەوان نەخۆشی ڤایکینگ مامە نزم ڕەواندز ڤاریا مۆم زانا خوێ گیڤارا',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 8, 'exercise_id' => 20, 'title' => 'ڕیزی خوارەوە - ٨', 'content_type' => 'sentences', 'content' => 'چۆن پێچەوانە جەمەلۆن زەوی زەنگین ڤاریا چی باران چاک ناوازە ناشڤێل مرۆڤایەتیی مامۆستا خۆشگوزەرانی خێزان شرۆڤەکار نڤیشکان زستان  بەگژداچوونەوە کانزا خۆشه‌ویستی نان مایەپووچبوون نیوزلەندا',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 9, 'exercise_id' => 20, 'title' => 'ڕیزی خوارەوە - ٩', 'content_type' => 'sentences', 'content' => 'ڤییان ڕەواندز پێچەوانە زەنگین ڤایکینگ زۆن خێزان چیمەن مامۆستا خۆڵ مۆم زانکۆ خۆشگوزەرانی نەخۆشی نان زانا نیاز ڤایرۆس نانەواخانە خێمە خۆشه‌ویستی بەنزین مایەپووچبوون رۆژنامەڤان ناوازە تەنگپێهەڵچنین نزم کانزا نڤیشکان',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 10, 'exercise_id' => 20, 'title' => 'ڕیزی خوارەوە', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 21, 'title' => 'ووشەی شیفتەکان - ١', 'content_type' => 'sentences', 'content' => 'پاشان کوڕ عه‌مباری ڕێگە نەخۆشی ووشە خۆڵ مووچە شمشاڵ غازدا بنەچە قۆناغ تەنگپێهەڵچنین ڕەنگە ڕیز ناشڤێل باڵیۆز هیچ کچ خشت بچووک شت ئەمڕۆ ناوەڕاست خۆشه‌ویستی چەمچەماڵ تۆڕ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 21, 'title' => 'ووشەی شیفتەکان - ٢', 'content_type' => 'sentences', 'content' => 'ڕاست داغستان باش خورمەڵە تەڕەتیزە کەرنەڤاڵی عەمرە هۆشداری جامچی خۆشگوزەرانی ڕۆژ عیبری عەمرە شوێن شلیک قەڵادزێ قه‌ده‌غه‌ چی شەوچەرە شرۆڤەکار توتڕک',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 21, 'title' => 'ووشەی شیفتەکان - ٣', 'content_type' => 'sentences', 'content' => 'بەگژداچوونەوە چاک مایەپووچبوون چەماوە مەعکەرۆنی چەپ نڤیشکان چیمەن پێچەوانە درێغی چەوت بەغداد مەغریب عەرەبانە شنگال عەممان مەنجەڵ ناوچەکانمان زوڵم چۆن شەمشەمەکوێرە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 21, 'title' => 'ووشەی شیفتەکان - ٤', 'content_type' => 'sentences', 'content' => 'عیبری مەغریب چۆن چیمەن کچ داغستان پێچەوانە زوڵم قۆناغ کوڕ نەخۆشی بچووک بەغداد عەمرە شلیک شنگال چەمچەماڵ عه‌مباری مەعکەرۆنی هیچ شەوچەرە ڕاست چاک باش خشت مووچە باڵیۆز',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 21, 'title' => 'ووشەی شیفتەکان - ٥', 'content_type' => 'sentences', 'content' => 'غازدا ناوچەکانمان شوێن ڕۆژ شمشاڵ شت شرۆڤەکار پاشان چەپ مایەپووچبوون بنەچە خۆشگوزەرانی نڤیشکان ڕێگە توتڕک تۆڕ شەمشەمەکوێرە خورمەڵە چی خۆشه‌ویستی ناشڤێل',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 21, 'title' => 'ووشەی شیفتەکان - ٦', 'content_type' => 'sentences', 'content' => 'عەمرە خۆڵ ڕەنگە ئەمڕۆ جامچی ڕیز ناوەڕاست عەرەبانە هۆشداری تەڕەتیزە عەممان قه‌ده‌غه‌ مەنجەڵ کەرنەڤاڵی چەماوە بەگژداچوونەوە قەڵادزێ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 7, 'exercise_id' => 21, 'title' => 'ووشەی شیفتەکان - ٧', 'content_type' => 'sentences', 'content' => 'چیمەن چاک عەرەبانە عەمرە ووشە ڕاست شرۆڤەکار داغستان چی عەممان بەگژداچوونەوە ناوەڕاست کچ چەپ ڕیز کوڕ شەوچەرە کەرنەڤاڵی درێغی ناوچەکانمان خشت شنگال ناشڤێل',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 8, 'exercise_id' => 21, 'title' => 'ووشەی شیفتەکان - ٨', 'content_type' => 'sentences', 'content' => 'توتڕک عەمرە خورمەڵە چەمچەماڵ شمشاڵ غازدا مایەپووچبوون ڕێگە شەمشەمەکوێرە عیبری تەنگپێهەڵچنین خۆشه‌ویستی چۆن مووچە شوێن نەخۆشی قەڵادزێ جامچی تۆڕ مەنجەڵ',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 9, 'exercise_id' => 21, 'title' => 'ووشەی شیفتەکان', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 22, 'title' => 'خاڵبەندی - ١', 'content_type' => 'letters', 'content' => '؛ ‘’’ ؛ ‘’’ ؛ ‘’’ ؛ ‘’’ ؛ ‘’’ ؛ ‘’’ ؛ ‘’’ ؛ ‘’’ ‘’’ ؛؛؛ ‘’',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 22, 'title' => 'خاڵبەندی - ٢', 'content_type' => 'sentences', 'content' => 'سڵاو، چۆنن باشن. ئەمڕۆ… فێری کلیلی نوێ ئەبین، ئەویش خاڵبەندییەکانە.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 22, 'title' => 'خاڵبەندی - ٣', 'content_type' => 'sentences', 'content' => 'لە نووسینی دەقێکدا، سەرەڕای ڕەچاوکردنی کۆمەڵێ یاسا و ڕێسای نووسین، نووسەر دەبێ ڕەچاوی یاساکانی خاڵبەندییش بکات.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 22, 'title' => 'خاڵبەندی - ٤', 'content_type' => 'sentences', 'content' => 'دەقێک کە خاڵبەندی تێیدا ڕەچاو نەکرابێ، دەبێتە هۆی سەرلێشێواندن لە خوێنەر و، لە ئەنجامیشدا، بەهەڵەتێگەیشتن لە نووسراوەکە.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 22, 'title' => 'خاڵبەندی - ٥', 'content_type' => 'sentences', 'content' => 'خاڵ بۆر (؛) خاڵبۆر بۆ وچانگرتنێکی درێژتر لە بۆری ساده،‌ بەکار دەهێنرێت.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 22, 'title' => 'خاڵبەندی - ٦', 'content_type' => 'sentences', 'content' => 'خاڵ (.) لە کۆتاییی هەموو ڕستەیەکدا، جگە لە پرس و سەرسوڕمان.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 7, 'exercise_id' => 22, 'title' => 'خاڵبەندی - ٧', 'content_type' => 'sentences', 'content' => 'بۆر (،) نیشانەی پشوویەکی کورتە، لەو شوێنە دادەنرێ کە وا لە ڕستەکه بکات ئاسان بخوێنرێتەوە، ڕوون بێت و بەباشی تێ بگەیەنرێ.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 8, 'exercise_id' => 22, 'title' => 'خاڵبەندی', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 23, 'title' => 'خاڵبەندی پێشکەوتوو - ١', 'content_type' => 'sentences', 'content' => 'جووت خاڵ (:) لە پێش ئاخاوتنێکەوە کە وەک خۆی بگێڕدرێتەوە، یان بگوترێت.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 23, 'title' => 'خاڵبەندی پێشکەوتوو - ٢', 'content_type' => 'sentences', 'content' => 'نیشانەی پرس (؟) دەخرێتە کۆتاییی ئەو ڕستانەی کە پرسیاریان تێدایە؟',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 23, 'title' => 'خاڵبەندی پێشکەوتوو - ٣', 'content_type' => 'sentences', 'content' => 'یشانەی سەرسوڕمان (!) ئەم نیشانەیە هەم بۆ سەرسوڕمانە، هەم بۆ ئەمرکردن یان داواکردنە!',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 23, 'title' => 'خاڵبەندی پێشکەوتوو - ٤', 'content_type' => 'sentences', 'content' => 'سێ خاڵ (...) سێ خاڵ لە بری وشە، یان ڕستەیەک کە قرتێنراوە، بە مەبەستی کورتکردنەوە بەکار دەبرێ.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 23, 'title' => 'خاڵبەندی پێشکەوتوو - ٥', 'content_type' => 'sentences', 'content' => 'هێڵی لار (/) ۆ نووسینی ڕێکەوت کە بە ژمارە دەنووسرێ، کەڵک لە هێڵی لاری (/) وەردەگرین.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 23, 'title' => 'خاڵبەندی پێشکەوتوو', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ١', 'content_type' => 'sentences', 'content' => 'میرنشینە کوردییەکان بریتی بوون لە: ئەردەڵان، سۆران، بادینان، بابان، هەکاری و بۆتان.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ٢', 'content_type' => 'sentences', 'content' => 'ئاسمانی ئەدەبی کوردی پڕە لە ئەستێرەی درەوشاوە:-نالی، مەحوی، گۆران، هێمن و هتد.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ٣', 'content_type' => 'sentences', 'content' => 'کچینە، هەوڵ بدەن، بە هەوڵدان دەگەنە ئامانج.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ٤', 'content_type' => 'sentences', 'content' => 'مەستوورەی کوردستانی، هۆنەر و مێژوونووس، لە ڕۆژهەڵاتی کوردستاندا دەژیا.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ٥', 'content_type' => 'sentences', 'content' => 'پێشمەرگە بە برسییەتی و تینوویەتی، بە هیلاکی و ماندوویەتی، کۆڵی لێ نادات.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ٦', 'content_type' => 'sentences', 'content' => 'شنۆ ویستی بچێ بۆ شایی، جلی لەبەر کرد، خۆی ڕازاندەوە، تەلەفۆنی لە هاوڕێکانی کرد، یەکیان گرت، خۆیان گەیاندە شایییەکە.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 7, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ٧', 'content_type' => 'sentences', 'content' => 'ئایا دەزانی یەکەم ڕۆژنامەی کوردی چ ساڵی دەر چوو؟',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 8, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ٨', 'content_type' => 'sentences', 'content' => 'لەم ساڵانەی دوایییەدا، کوردێکی زۆر پەڕیوەی هەندەران بوون؛ کوردەکان دەتوانن سوودێکی زۆر بە گەلەکەیان بگەیەنن.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 9, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ٩', 'content_type' => 'sentences', 'content' => 'زانایان “زمان” بە کۆڵەکەی نەتەوە دادەنێن.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 10, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ١٠', 'content_type' => 'sentences', 'content' => 'من "مێژوو" بە چرای تاریکستانی داهاتوو دەزانم.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 11, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ١١', 'content_type' => 'sentences', 'content' => 'کاتێ بتوانین “ئەلفبێ جۆربەجۆرە کوردییەکان” بکەین بە “یەک ئەلفوبێ”، ئەو کاتە گەلێ کێشەمان چارەسەر دەبێ.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 12, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ١٢', 'content_type' => 'sentences', 'content' => 'قازی موحەممەد، چاونەترس ڕووی تێ کردن: “ئێوە ئەمڕۆ قازی موحەممەدێک دەکوژن، سبەینێ لە هەر دڵۆپە خوێنێکی من، سەدان قازی موحەممەدی تر سەر هەڵدەدەن.”',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 13, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ١٣', 'content_type' => 'sentences', 'content' => 'شاری سلێمانی (کە کەوتۆتە دامێنی چیای ئەزمەڕ) سلێمان پاشای بابان بنیادی ناوە.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 14, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ١٤', 'content_type' => 'sentences', 'content' => 'سنووری دەوڵەتی حەسنەوی (٩٤١ ـ ١٠١٤) که پارە و پوولیشیان هەڵکەندبوو،‌ هەمەدان، مەهاباد، کرماشان و شارەزوور بوو.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 15, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ١٥', 'content_type' => 'sentences', 'content' => 'من سنە، کرماشان، مەهاباد، سلێمانی، کەرکووک و ...م چاو پێ کەوتووە.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 16, 'exercise_id' => 24, 'title' => 'ڕستەی کورت - ١٦', 'content_type' => 'sentences', 'content' => 'شاری کەرکووک لە ١٠/٤/٢٠٠٣ ڕزگار کرا.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 17, 'exercise_id' => 24, 'title' => 'ڕستەی کورت', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 25, 'title' => 'پەرەگرافی کورت - ١', 'content_type' => 'sentences', 'content' => 'لە کابرایەکی کوردیان پرسی بە چیدا ئەزانی خوا، یەکێکە و دوو نییە؟ ئەویش وتی: بە ئاشەکەی ماڵی لالەما؛ تا ئەو وەختەی کە هەر خۆی بوو دایمە گەڕ بوو،',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 25, 'title' => 'پەرەگرافی کورت - ٢', 'content_type' => 'sentences', 'content' => 'ێستا کە لەگەڵ حەمەی شەفێ بوون بە شەریک، ڕۆژێک ئەگەڕێ و چوار ڕۆژ ئەوەستێ. خواش ئەگەر یەکێکی کەی لەگەڵ بووایە ئیشەکەی وەکوو ئاشەکەی لالەمی لێ ئەهات!',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 25, 'title' => 'پەرەگرافی کورت - ٣', 'content_type' => 'sentences', 'content' => 'کابرایەک بوو بە میوانی ماڵە کوردێک، نانیان دانا چێشتەکە زۆر گەرم بوو، کابرای میوان هەموو دەم و ددانی سووتا!',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 25, 'title' => 'پەرەگرافی کورت - ٤', 'content_type' => 'sentences', 'content' => 'لە تاوانا سەری بەرز کردەوە و سەیرێکی دارەڕای خانووەکەی کرد، بۆ ئەوەی خاوەن - ماڵەکە هەستی پێ نەکا،',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 25, 'title' => 'پەرەگرافی کورت - ٥', 'content_type' => 'sentences', 'content' => 'پێی وت: ئەرێ برا ئەم خانووەت بە چەندی دروست کردووە؟ کابرای خاوەن ماڵیش وتی: بە دوو فوو و سەبرێک.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 25, 'title' => 'پەرەگرافی کورت', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ١', 'content_type' => 'sentences', 'content' => 'چومە چەمی چەقان چەقەڵ چەڵتوکی ئەتەقان',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ٢', 'content_type' => 'sentences', 'content' => 'هەموو ڕۆژێک دەستپێکی ژیانێکی نوێیە',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ٣', 'content_type' => 'sentences', 'content' => 'ژورێکی بێ کتێب وەک جەستەیەکی بێ ڕۆح وایە.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ٤', 'content_type' => 'sentences', 'content' => 'دەستبدەرە ئەو گۆڕانکارییەی کە ئارەزوی بینینی دەکەیت لە جیهاندا.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ٥', 'content_type' => 'sentences', 'content' => 'بەو شێوەیە بژی کە سبەینێ ئەمریت. بەردەوام فێربە وەک ئەوەی بۆ هەمیشە ئەژیت.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ٦', 'content_type' => 'sentences', 'content' => 'بەبێ مۆسیقا ژیان هەڵەدەبوو.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 7, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ٧', 'content_type' => 'sentences', 'content' => 'کاتێک فێری خوێندنەوە بوویت، بۆ هەمیشە ئازاد دەبیت.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 8, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ٨', 'content_type' => 'sentences', 'content' => 'من شکستم نەهێنا. دە هەزار ڕێگام دۆزییەوە کە کاریان نەدەکرد.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 9, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ٩', 'content_type' => 'sentences', 'content' => 'ژیان ئەوە نییە خۆت بدۆزیتەوە. ژيان ده‌رباره‌ی خۆ دروست کردنە.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 10, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ١٠', 'content_type' => 'sentences', 'content' => 'ئەوەی لە تواناتدایە بیکە، بەو شتەی کە هەتە، لەهەرکوێ بویت.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 11, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ١١', 'content_type' => 'sentences', 'content' => 'زیرەکی ڕاستەقینە ئەوەیە کە بزانیت هیچ نازانیت.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 12, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ١٢', 'content_type' => 'sentences', 'content' => 'شەرم مەکە لە نەزانین، بپرسە. نەزان ئەو کەسەیە کە پرسیار ناکات.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 13, 'exercise_id' => 26, 'title' => 'مەشقی خێرا - ١٣', 'content_type' => 'sentences', 'content' => 'مانای ڕاستەقینەی ژیان پرسیارکردنە، هیچ سنورێک بۆ پرسیارکردن نییە.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 14, 'exercise_id' => 26, 'title' => 'مەشقی خێرا', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            ['lesson_id' => 2, 'order' => 1, 'exercise_id' => 27, 'title' => 'پێداچونەوەی ناوەندی - ١', 'content_type' => 'sentences', 'content' => 'ماڵێک سێ کچیان دەبێت کە زمانیان فسکە.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 2, 'exercise_id' => 27, 'title' => 'پێداچونەوەی ناوەندی - ٢', 'content_type' => 'sentences', 'content' => 'ڕۆژێک میوانیان دێت بۆ خوازبێنی یەکێک لە کچەکان،',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 3, 'exercise_id' => 27, 'title' => 'پێداچونەوەی ناوەندی - ٣', 'content_type' => 'sentences', 'content' => 'دایکیان پێیان دەڵێت: هیچ نەڵێن تاوەکو میوانەکان دەڕۆنەوە.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 4, 'exercise_id' => 27, 'title' => 'پێداچونەوەی ناوەندی - ٤', 'content_type' => 'sentences', 'content' => 'لە کاتی میواندارییەکەیا میوانەکان هەرچەند دەکەن کچەکان بدوێنن تا هەڵیانبسەنگێنن، بەڵام بێ سوودەو وورتەیان لێنایەت.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 5, 'exercise_id' => 27, 'title' => 'پێداچونەوەی ناوەندی - ٥', 'content_type' => 'sentences', 'content' => 'لەم مشتومڕەیا دەبن، لە ناکاو مشکێک دەردەپەڕێت.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 6, 'exercise_id' => 27, 'title' => 'پێداچونەوەی ناوەندی - ٦', 'content_type' => 'sentences', 'content' => 'کچە بچوکەکەیان دەڵێت: ئەها ئەو مستە!',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 7, 'exercise_id' => 27, 'title' => 'پێداچونەوەی ناوەندی - ٧', 'content_type' => 'sentences', 'content' => 'کچە ناوەنجییەکەش: دەڵێت وەلا چۆیە تونەتە!',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 8, 'exercise_id' => 27, 'title' => 'پێداچونەوەی ناوەندی - ٨', 'content_type' => 'sentences', 'content' => 'کچە گەورەکەش کە خۆی لەوانی تر بە زیرەکتر دەزانێت،',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 9, 'exercise_id' => 27, 'title' => 'پێداچونەوەی ناوەندی - ٩', 'content_type' => 'sentences', 'content' => 'دەڵێت: شتر و متر خۆم قسەم نەتر.',  'extra' => 60, 'locale' => 'ckb'],
            ['lesson_id' => 2, 'order' => 10, 'exercise_id' => 27, 'title' => 'پێداچونەوەی ناوەندی', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'ckb'],

            // ['lesson_id' => 1, 'order' => 1, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ١', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 2, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ٢', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 3, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ٣', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 4, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ٤', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 5, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ٥', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 6, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ٦', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 7, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ٧', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 8, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ٨', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 9, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ٩', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 10, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ١٠', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 11, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ١١', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
            // ['lesson_id' => 1, 'order' => 12, 'exercise_id' => 5, 'title' => 'ۆ، ب لەگەڵ ا - ١٢', 'content_type' => 'sentences', 'content' => '',  'extra' => 60, 'locale' => 'ckb'],
        ];

        foreach ($screens as $screenData) {
            Screen::create($screenData);
        }
    }
}
