<?php

namespace Database\Seeders;

use App\Models\Screen;
use Illuminate\Database\Seeder;
use  App\Services\LetterConverter;

class ScreenSeederBeginnerEN extends Seeder
{

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $converter = new LetterConverter();
        $screens = [
            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 28, 'title' => 'J intro', 'content_type' => 'intro', 'content' => 'j',  'extra' => "j", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 28, 'title' => 'J, F, and Space - 1', 'content_type' => 'letters', 'content' => 'jjjjjjjj',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 28, 'title' => 'F intro', 'content_type' => 'intro', 'content' => 'f',  'extra' => "f", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 28, 'title' => 'J, F, and Space - 2', 'content_type' => 'letters', 'content' => 'fffjfffjfffjfffj',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 28, 'title' => 'J, F, and Space - 3', 'content_type' => 'letters', 'content' => 'jjffjjffjjjfffjfjffjjfjfjfffjjffjjfffjjjjffjfjffjfjff',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 28, 'title' => 'J, F, and Space - 4', 'content_type' => 'letters', 'content' => 'j j j j j j j j j',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 28, 'title' => 'J, F, and Space - 5', 'content_type' => 'letters', 'content' => 'jjj ffffff jjjff jj ff',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 28, 'title' => 'J, F, and Space - 6', 'content_type' => 'letters', 'content' => 'jjjfffjjfffjjfjfjfffjjjjff',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 28, 'title' => 'J, F, and Space - 7', 'content_type' => 'letters', 'content' => 'jjf jjf jjf jjf jj ff jj',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 28, 'title' => 'J, F, and Space - 8', 'content_type' => 'letters', 'content' => 'jfjjfjjfjjfjjfjjfjjfjjfjjfjfjffjffjffjffjffjffjf',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 28, 'title' => 'J, F, and Space - 9', 'content_type' => 'letters', 'content' => 'jjff fffjj fjjfjfj fjfjfjjf fff ffjjj jfjjjf ffjf',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 28, 'title' => 'J, F, and Space - 10', 'content_type' => 'letters', 'content' => 'fjfjjjffjjjfffjjjjffffjjjjjfffffjjjjffffjffjjjfffjjfjfjf',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 28, 'title' => 'J, F, and Space - 11', 'content_type' => 'letters', 'content' => 'jjfjff ffjfjj jffjf jfjf ffjffj ffjjjffj fjfjfjfj',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 28, 'title' => 'J, F, and Space', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 1', 'content_type' => 'letters', 'content' => 'uuujuuujuujjuujjuj uu ju',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 2', 'content_type' => 'letters', 'content' => 'rrrfrrrfrrffrrffrf rr fr',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 3', 'content_type' => 'letters', 'content' => 'uurrrruruururruuurururrruuurrruuuurrurruuurururru',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 4', 'content_type' => 'letters', 'content' => 'j uuu jjf rrr ffuuu j uufr fr fr',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 5', 'content_type' => 'letters', 'content' => 'kkkkkkkkkkkkjjjjkkjjkkjj',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 6', 'content_type' => 'letters', 'content' => 'jjjkfffrjjkkffrrrrffkkjrrrfkkkjrrrrkkkkjkfrjkkfrrkjrffrj',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 7', 'content_type' => 'letters', 'content' => 'kkjfrrkkjfrrkkjfrrkkjfrrkkjfrr',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 8', 'content_type' => 'letters', 'content' => 'kkkk uuuu rrrr uuuu kkkk rrrr uuuu kkkk uuuu rrrr rr uu kk',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 9', 'content_type' => 'letters', 'content' => 'urkkrkrkukkrruurkrkurukkruururkkkkurkururukrukurku',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 10', 'content_type' => 'letters', 'content' => 'kuf rukkur ruffur kurfkuf rukkkur ruff',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 11', 'content_type' => 'letters', 'content' => 'ruff fur ruff fur kruff furr fur ruff kruff furr ruff fur',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 12', 'content_type' => 'letters', 'content' => 'urkjjrukkurjjjurkkjrkukurjjjurkkjrkukkrr',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 13, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 13', 'content_type' => 'letters', 'content' => 'rufkj jufr kjufrk jrkufjk fjkfur',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 14, 'exercise_id' => 29, 'title' => 'U, R, and K Keys - 14', 'content_type' => 'letters', 'content' => 'kurr kurrf kufr jjuu jjrr jjuu jjrr kfur kkjjuurrff uujjrrffkk jufrk rff furjk',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 15, 'exercise_id' => 29, 'title' => 'U, R, and K Keys', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 1', 'content_type' => 'letters', 'content' => 'ddddffffddddffffdffdffdd',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 2', 'content_type' => 'letters', 'content' => 'iiiikkkkiiiikkkkikkikkii',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 3', 'content_type' => 'letters', 'content' => 'ddiidddiiiiddiididididiiidiidididididiiiddddiiiddii',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 4', 'content_type' => 'letters', 'content' => 'eeeeddddeeeeddddeeddeeddeeddffee',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 5', 'content_type' => 'letters', 'content' => 'eeeddddiiiikkkkeeeieeiieiiiieeeiieieieeieie',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 6', 'content_type' => 'letters', 'content' => 'ddddeeddddeeddddeekkikkikkikiikiikiidekidekiddekkidekidedkikdedkikded',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 7', 'content_type' => 'letters', 'content' => 'jid kid rid eid jid kid rid eid kirk kird kirf kire kidr fied',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 8', 'content_type' => 'letters', 'content' => 'fred did kik red fire fed duke kirk fed fred fur fire if red kk',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 9', 'content_type' => 'letters', 'content' => 'direduedukefedfeudfeudfirfirefiredfriedfuridifireirkjukeredrefridrideriferude',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 10', 'content_type' => 'letters', 'content' => 'fed euk erk eik erk eik dif def kid ked iure urd',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 30, 'title' => 'D, E, and I Keys - 11', 'content_type' => 'letters', 'content' => 'fire jure feud juke jedi fuji rudie fried fired irked fired jerid juked duiker juried dire',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 30, 'title' => 'D, E, and I Keys', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 1', 'content_type' => 'letters', 'content' => 'cdcdccddccddccddccccddcc',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 2', 'content_type' => 'letters', 'content' => 'njnjnjnjnnjjnnjjnnnnjjjj',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 3', 'content_type' => 'letters', 'content' => 'ccnnnnccnnncnncnnncccnnnncnncnnncnccncccncnncnccn',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 4', 'content_type' => 'letters', 'content' => 'dcc jnndcc jnnccd nnjdcc jnnjdcnncjdncjdncjd',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 5', 'content_type' => 'letters', 'content' => 'cdcnjncnncnncnnnccnccdcjnncc',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 6', 'content_type' => 'letters', 'content' => 'gfgfgfgfggffggffggggffff',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 7', 'content_type' => 'letters', 'content' => 'nnjjggggffnnngnngnggnnnjjjgggfffnnngfgngnjgngnn',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 8', 'content_type' => 'letters', 'content' => 'fgg jnn ggg nnn fnf jgj fgg jnn ggn nng fgfg jnjn ngng fgfg',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 9', 'content_type' => 'letters', 'content' => 'en in ne nu un ug id gu ig nie nid neg ned ide gue gin cid cud ecu ice',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 10', 'content_type' => 'letters', 'content' => 'cure end diner cider end cued dice induce deduce cid duck dine ice iced',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 11', 'content_type' => 'letters', 'content' => 'nnjjuukkiiggffgfgddccddeegfdceeeddffggccnjkiu',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 31, 'title' => 'C, G, and N Keys - 12', 'content_type' => 'letters', 'content' => 'can card cure dine dirt duke earn fire girl kind knife large merge niece nice rain range rice surge tire urge',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 13, 'exercise_id' => 31, 'title' => 'C, G, and N Keys', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 32, 'title' => 'Beginner Review 1 - 1', 'content_type' => 'letters', 'content' => 'jjj fff uuu rrr kkk ddd eee iii ccc ggg nnn jjj j f u r k d e i c g n j r d k u f e j i g n c r',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 32, 'title' => 'Beginner Review 1 - 2', 'content_type' => 'letters', 'content' => 'jfurkdeicgnrdkufejigncnurdiekfciundifngkrjfnu',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 32, 'title' => 'Beginner Review 1 - 3', 'content_type' => 'letters', 'content' => 'de di du ed ef en er fe fi id if in ki ne nu',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 32, 'title' => 'Beginner Review 1 - 4', 'content_type' => 'letters', 'content' => 'cgi cru cud due cur def den der dig',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 32, 'title' => 'Beginner Review 1 - 5', 'content_type' => 'letters', 'content' => 'due dug diu dun ecu end eng erg ern fed feu fid fie figfin fir fud fug fun fur',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 32, 'title' => 'Beginner Review 1 - 6', 'content_type' => 'letters', 'content' => 'gid gie gin gnu ice ick ide ink ire irk jin jug jen kef keg ken kif kin kir kue',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 32, 'title' => 'Beginner Review 1 - 7', 'content_type' => 'letters', 'content' => 'rung rune ruin rude rink ring rind ride cure curd cued dunk dune duke duck fine',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 32, 'title' => 'Beginner Review 1 - 8', 'content_type' => 'letters', 'content' => 'dice dine ding dire dirkdreg duce duck dukedune dungdunk dureecru fend fern feud fide find fine',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 32, 'title' => 'Beginner Review 1 - 9', 'content_type' => 'letters', 'content' => 'fink fire fern friend fund funk gird grid grin gunk iced jink junk juke june junk king kerf kern kind',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 32, 'title' => 'Beginner Review 1 - 10', 'content_type' => 'letters', 'content' => 'rain nice knife large can dine fire cure range rice surge fringe indulge urge cringe kind jungle girl ridge',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 32, 'title' => 'Beginner Review 1', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 1', 'content_type' => 'letters', 'content' => 'ttttttttffffttttttffttff',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 2', 'content_type' => 'letters', 'content' => 'llllllllkkkkllllllkkllkk',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 3', 'content_type' => 'letters', 'content' => 'ttlltltlttttllllttffllkkllkkttffttff',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 4', 'content_type' => 'letters', 'content' => 'f ttt ffttt fttflll k llft kl ft ffttkkll',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 5', 'content_type' => 'letters', 'content' => 'ssssssssddddsssssdsdsdsdsdfsdfsd',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 6', 'content_type' => 'letters', 'content' => 'sslllslslsslsllslslslllslsslssllllsssllslslssllsls',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 7', 'content_type' => 'letters', 'content' => 'tsltlslstllslsslsttttllssstsltltttlssltltslsssttll',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 8', 'content_type' => 'letters', 'content' => 'esstisitlisisttetiusutlielislitseiselsetsitsuesuitelrestietiltistui',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 9', 'content_type' => 'letters', 'content' => 'slug ties tile silt lute lets stile nicest signed tunic uncles genius',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 10', 'content_type' => 'letters', 'content' => 'king signet single suited united luces diner cutie glens list guile',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 11', 'content_type' => 'letters', 'content' => 'nicest suited tunic stick trunk dents cutie glens signet single suited united signed',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 33, 'title' => 'T, S, and L Keys - 12', 'content_type' => 'letters', 'content' => 'Stars List Settle Slate Steal Stale Sales Castle Talented Slates Last Salt Least Slit Skill Taste Lists',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 13, 'exercise_id' => 33, 'title' => 'T, S, and L Keys', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 1', 'content_type' => 'letters', 'content' => 'oooooooolllloooolloolloo',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 2', 'content_type' => 'letters', 'content' => 'bbbbbbbbffffbbbbffbbffbb',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 3', 'content_type' => 'letters', 'content' => 'bbbfffooolllbbbfffolbbobbbobbbffggbboollkkbgfbgfolkolk',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 4', 'content_type' => 'letters', 'content' => 'loo fbb loo fbb ool bbf loo fbb flob bofl bofl bofl bofl bofl bofl flob',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 5', 'content_type' => 'letters', 'content' => 'obb obb o b b boo boo b o o obo bob bob obo o o b boo boo b b o oob boo',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 6', 'content_type' => 'letters', 'content' => 'aaaaaaaassssaaaasasasasa',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 7', 'content_type' => 'letters', 'content' => 'bbaaaa bbbabb abaabbb aaabbb aabab ababbbb aaabbb aabbaaba',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 8', 'content_type' => 'letters', 'content' => 'ob bo ba ab ba bo ob aboboa oba ab',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 9', 'content_type' => 'letters', 'content' => 'tab sob sat oat lot lob lab tabs slot slob slab salt lost',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 10', 'content_type' => 'letters', 'content' => 'togas tango talon slant slang salon longs loans goats goals',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 11', 'content_type' => 'letters', 'content' => 'gnats globs gloat bolts boats boast blots blogs bloat blats blast baton angst altos along',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 12', 'content_type' => 'letters', 'content' => 'abides adobes bailed bard coned conga dance design',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 13, 'exercise_id' => 34, 'title' => 'O, B, and A Keys - 13', 'content_type' => 'letters', 'content' => 'horn drain brag bark iron adore care chord heard guard bird organ child bored range grain cargo brown ',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 14, 'exercise_id' => 34, 'title' => 'O, B, and A Keys', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 1', 'content_type' => 'letters', 'content' => 'vvvvvvvvffffvvvvffvvffvv',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 2', 'content_type' => 'letters', 'content' => 'hhhhhhhhjjjjhhhhjjhhjjhh',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 3', 'content_type' => 'letters', 'content' => 'vvffhhjjvvvffffhhjjvvhhvhvhhvfhjhjvvffhjklhvfrfvfr',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 4', 'content_type' => 'letters', 'content' => 'fvjhvfhjvvvhhhfvfjhjvvvhhhfvjhvfhjvvvhhhfvfjhjvvvhhh',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 5', 'content_type' => 'letters', 'content' => 'mmmmmmmmjjjjmmmmjjmmjjmm',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 6', 'content_type' => 'letters', 'content' => 'mjmjmjvfvfvfmmmjjjvvffmvmvmvmvmvfvvvmmmjjj',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 7', 'content_type' => 'letters', 'content' => 'jmjhjmjh jmjh jmjh hjm hjm mjh mjh jhj jmj hhh jjj mmm jjj hhh jjj mmm m j h j',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 8', 'content_type' => 'letters', 'content' => 'vhm vhm mvh mvh hmv hmv mmh mmv mmh mmv mmh mmv vvh vvm hhv mmh vhm vmv',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 9', 'content_type' => 'letters', 'content' => 'ab ah am ba bo ha hm ma mo oh om av bah bamm',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 10', 'content_type' => 'letters', 'content' => 'hams hang hant hats hobs hogs holt host mobs most moth mogs oval vang vans vast vats volt',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 11', 'content_type' => 'letters', 'content' => 'moth lamb oval halo vans vast vats hacks halos tombs volts havoc hacks formal fourth frocks frugal fulgor',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 12', 'content_type' => 'letters', 'content' => 'halo hacks formal ovals halo hacks halo hacks formal ovals halo hacks',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 13, 'exercise_id' => 35, 'title' => 'V, H, and M Keys - 13', 'content_type' => 'letters', 'content' => 'vampire maverick vehicle heaven hammer marvel haven mauve move hover maven macho havoc value mavenly hovering',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 14, 'exercise_id' => 35, 'title' => 'V, H, and M Keys', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 1', 'content_type' => 'letters', 'content' => ',,,,,,,,kkkk,,,,kk,,kk,,',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 2', 'content_type' => 'letters', 'content' => '……..llll….ll..ll..',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 3', 'content_type' => 'letters', 'content' => ',,,,kkkk….llll,,klkl.,kl.,kl.,kkll..,,',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 4', 'content_type' => 'letters', 'content' => 'l.k,l..k,,..l,,k.l,k,,..,. ,. .,',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 5', 'content_type' => 'letters', 'content' => 'zzzzzzzzaaaazzzzaazzaazzazazazaz',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 6', 'content_type' => 'letters', 'content' => 'zap, zep. zip. quiz, zap, zep. zip, quiz.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 7', 'content_type' => 'letters', 'content' => 'raze, rez. ritz, ritzy. terza, za. zaz, ritz.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 8', 'content_type' => 'letters', 'content' => 'za, zeta. zero. zit, zoa, zozzy.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 9', 'content_type' => 'letters', 'content' => 'wimmy. wam. wam, wozzle,',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 10', 'content_type' => 'letters', 'content' => 'l.k.j.h.g.f.d.s.d.f.g.h.j.k.l.u.r.i.e.r.t.u.m.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 11', 'content_type' => 'letters', 'content' => 'j.k.l.u.i.o.m.n.h.g.f,d,s,a,t,r,e,b,v,c,',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 12', 'content_type' => 'letters', 'content' => 'job. ham. hob. jab, zjam, mob, ohm. ova,',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 13, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 13', 'content_type' => 'letters', 'content' => 'foam. jamb, lamb. lash, zlast. lath, loath. lobs.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 14, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 14', 'content_type' => 'letters', 'content' => 'farm, faro, foam, fork, zform, harm. zhear. hour. jamb. jour.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 15, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 15', 'content_type' => 'letters', 'content' => 'ovum, raku, roam, abhor, abohm, soar, zsofa. sofr, soma. sorb.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 16, 'exercise_id' => 36, 'title' => 'Z, Period and Comma - 16', 'content_type' => 'letters', 'content' => 'maze, maize, muzzle, zigzag, zealous, zingy, zodiac, zippy, zesty, zoo.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 17, 'exercise_id' => 36, 'title' => 'Z, Period and Comma', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 37, 'title' => 'Beginner Review 2 - 1', 'content_type' => 'letters', 'content' => 'ab ae ah ai al am as a. ba be i. bo eh el em es ha h. hi hm il is it la le li o. ma me mi mo oe',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 37, 'title' => 'Beginner Review 2 - 2', 'content_type' => 'letters', 'content' => 'astb vast bvo. ,o., hmhm astb vast bvo. ,o., hmhm astb vast bvo. ,o., hmhm',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 37, 'title' => 'Beginner Review 2 - 3', 'content_type' => 'letters', 'content' => 'bis bit boa bos bot eat elm els ems est eta eth hae hamm',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 37, 'title' => 'Beginner Review 2 - 4', 'content_type' => 'letters', 'content' => 'hoi hot ism ist its lab lam las lat lav lea lei leo let lev lib lie lis lit loa lob lot',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 37, 'title' => 'Beginner Review 2 - 5', 'content_type' => 'letters', 'content' => 'mas mat meaz mel met mho mib milz mis moa mob moh mol mosz mot oat oba obe obi oes ohm ohsz oie oil',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 37, 'title' => 'Beginner Review 2 - 6', 'content_type' => 'letters', 'content' => 'ole oms ose ova sab sae sal sat sea sei sel set sha she sib sim sit sob soi sol sot tab tae tam',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 37, 'title' => 'Beginner Review 2 - 7', 'content_type' => 'letters', 'content' => 'abet able aims alms aloez also alto ambo atom avis baht bail bait bale balmz base bash bate bath bats',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 37, 'title' => 'Beginner Review 2 - 8', 'content_type' => 'letters', 'content' => 'beam beat beltz best beta bets bias bile bise bite bits blah blat blot boat boilz bola bole bolt bosh',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 37, 'title' => 'Beginner Review 2 - 9', 'content_type' => 'letters', 'content' => 'both east eats elms emit evil hail hale halo halsz halt zhams hate hats have heal heat helm hems hest',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 37, 'title' => 'Beginner Review 2 - 10', 'content_type' => 'letters', 'content' => 'move muzzle, hover haven havoc zesty, heaven zealous, mauve vehicle zippy, hammer maven zoo. zodiac, zigzag, hovering',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 37, 'title' => 'Beginner Review 2', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 1', 'content_type' => 'letters', 'content' => 'wwwwwwwwsssswwwwsswwssww',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 2', 'content_type' => 'letters', 'content' => ';;;;;;;;llll;;;;ll;;ll;;',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 3', 'content_type' => 'letters', 'content' => 'wwss;;llws;lw;;w;www;;;wwss;;ll;;llsswwsswwll;;',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 4', 'content_type' => 'letters', 'content' => 'sww l;;;sww l;;ls www ss www l ;;; l ;;;l',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 5', 'content_type' => 'letters', 'content' => 'xxxxxxxxssssxxxxssxxssxx',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 6', 'content_type' => 'letters', 'content' => 'xxss;;;llxxss;lxs;lxxssww;lxsw;;;lllxxsswwssxxssww;;ll;;lll',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 7', 'content_type' => 'letters', 'content' => 'sxs sws sxs sws wsxz wsx xsw xsw wsxs xsws wxwxwz xxxx wwww xx ww sw xs s',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 8', 'content_type' => 'letters', 'content' => 'www xxx ;;; wx; ;xw wwx ww; sxsw l;;l ;w;x ;;w ;;x x;x s;s w;w wxw xwx ww; xxw',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 9', 'content_type' => 'letters', 'content' => 'hex how; ho; maw maxx; min; mew; owe vaw; vex; vowz;',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 10', 'content_type' => 'letters', 'content' => 'avow; exam; meow; view; voix; wave; wham; whim;',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 11', 'content_type' => 'letters', 'content' => 'wham; what; wheat; whet wax; taxz; vex; ox; mix;',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 12', 'content_type' => 'letters', 'content' => 'texan. toxicz; toxin, twainz; vixen. waxen; white,',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 13, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 13', 'content_type' => 'letters', 'content' => 'wince, woman; wovenz. anoxic; unmix, varix; wall;',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 14, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys - 14', 'content_type' => 'letters', 'content' => 'zealousness zippy zesty, zoom; zoomed zooming zoo; waxen waxing, waxy; xenon; xylophone zydeco;',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 15, 'exercise_id' => 38, 'title' => 'W, X, and ; Keys', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 1', 'content_type' => 'letters', 'content' => 'qqqqqqqqaaaaqqqqaaqqaaqq',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 2', 'content_type' => 'letters', 'content' => 'yyyyyyyyjjjjyyyyjjyyjjyy',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 3', 'content_type' => 'letters', 'content' => 'qqaayjqayyyjjjqqqyyyqqyyyqqaaaqqyyjjjyyyqayj',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 4', 'content_type' => 'letters', 'content' => 'qqqjjyyaqqqyjyjqqqajyyyaqqqjyyy',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 5', 'content_type' => 'letters', 'content' => 'pppppppp;;;;pppp;;pp;;pp;p;p;p;p',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 6', 'content_type' => 'letters', 'content' => 'qqppqppqqqqqaaappp;;;p;p;qaqapq;apq;apq;aqaqaqap;p;p;',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 7', 'content_type' => 'letters', 'content' => 'ppyyyppyyyyjjhhyyjjhhyyjjhhyypp;;llpp;;llpp;;lloopp;;lloo',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 8', 'content_type' => 'letters', 'content' => 'aqjy;pqayap;;apqqp;ajy;paqjyyjqap;jjyqqa;;pppyjjqaap',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 9', 'content_type' => 'letters', 'content' => 'ax ay ex. ox oy we. woz xi ya; way wax yaw. wyez;',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 10', 'content_type' => 'letters', 'content' => 'yea, wavy queen panic yarnz. yea, wavy queen panic yarn.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 11', 'content_type' => 'letters', 'content' => 'qua quag; quay quez. quean, quince, quo, quionz;',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 12', 'content_type' => 'letters', 'content' => 'pac pacer, pacing, pack. packer, packing, page.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 13, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 13', 'content_type' => 'letters', 'content' => 'panic. par parce, pare parzi paring. parkz, pave',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 14, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 14', 'content_type' => 'letters', 'content' => 'paw pawing pax paying peaking; pear. pecan perk',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 15, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 15', 'content_type' => 'letters', 'content' => 'yank yap, yarn, yawning yawp. yearnz yew yoga yogi',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 16, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys - 16', 'content_type' => 'letters', 'content' => 'pygmy quay query quirky pyro pyre yappy yacht yank yawn yoyo quack quackery quagmire quarry quarryman puppy pylon pyrotechnics.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 17, 'exercise_id' => 39, 'title' => 'Q, Y, and P Keys', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 1', 'content_type' => 'letters', 'content' => 'jjj fff jjj fff jjj fff jj ff jjf ffj ddd kkd ddk kkd ddd kkd dd kk ddk kkd sss lll sss lll sss lll ss ll ssl lls aaa ;;; aaa ;;; aaa ;;; aaa ;;; aa ;; ggg hhh ggg hhh ggg hhh gg hh ggh hhg',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 2', 'content_type' => 'letters', 'content' => 'rrr uuu rrr uuu rrr uuu rr uu rru rru eee iii eee iii eee iii ee ii eei iie www ooo www ooo www ooo ww oo wwo oow qqq ppp qqq ppp qqq ppp qq pp qqp qqp ttt yyy ttt yyy ttt yyy tt yy tty yyt',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 3', 'content_type' => 'letters', 'content' => 'vvv mmm vvv mmm vvv mmm vv mm vvm mmv ccc ,,, ccc ,,, ccc ,,, ccc ,,, cc ,, xxx … xxx … xxx … xxx … xx .. zzz .,. zzz ,., zzz .,. zzz ,., zz .. bbb nnn bbb nnn bbb nnn bb nn bbn nnb',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 4', 'content_type' => 'letters', 'content' => 'add all alley aft agh ask afford ajar adapt arf salad sap slap slide shell sad sat shall shad',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 5', 'content_type' => 'letters', 'content' => 'dad dan decide dag darpa dart defer deter dash fan fantastic flirt fledgling fact flute flapper',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 6', 'content_type' => 'letters', 'content' => 'gandalf garden gas gad gallant gapless gallery has hag hat half haha ham halpert had handy',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 7', 'content_type' => 'letters', 'content' => 'jason jam jan jail jandy jag jandy jalp jaff jas kangaroo kayak kernite kerosene keystroke kiddy',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 8', 'content_type' => 'letters', 'content' => 'ladybug lamb lady last lamp lad laugh lard loss quartz quail quart quiver queen quarter',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 9', 'content_type' => 'letters', 'content' => 'wonder were wet weeds windowz well window well wonky eerie eep eight eyes eel ewe eeple ',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 10', 'content_type' => 'letters', 'content' => 'rose ring robot record report ruse tent tiger toe toad tooth toil tin', 'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 11', 'content_type' => 'letters', 'content' => 'yell yolk yoyo yolo yellow yelling yippy your upz upsidez utensils ur upper',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 12', 'content_type' => 'letters', 'content' => 'iris irate ite import idaho iconic icon irange owl orly ornate orchard ore oar',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 13, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 13', 'content_type' => 'letters', 'content' => 'portly pin pure pods privy pencil pig zigzag zerbra zero zucchini zipper zoo zithe ',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 14, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 14', 'content_type' => 'letters', 'content' => 'xenops ziphias xerox xenonz xylem xeres cow corn cup cone code cola coal cent cen',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 15, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 15', 'content_type' => 'letters', 'content' => 'vest volcano votez vulture violin vowels bee bird broomz bus booths benzine',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 16, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 16', 'content_type' => 'letters', 'content' => 'net nose nest notes nine numbers nuts milk mouse moth mopz moon moons moop',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 17, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 17', 'content_type' => 'letters', 'content' => 'i shall run to the store to pick up some milk. the land is solid, lad, and dad lovesz salads; many more times have you and jason run.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 18, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 18', 'content_type' => 'letters', 'content' => 'what do you think about that, asked the chikd. keep on tryingz to have fun while you run.',  'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 19, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up - 19', 'content_type' => 'letters', 'content' => 'this is the first full unit you have finished. i bet the keys are feeling more familiar by now. keep up your practice and you will do great work throughout all the lessons, do not give up. you will be rewarded with amazing typing skills.', 'extra' => "", 'locale' => 'en'],
            ['lesson_id' => 9, 'order' => 20, 'exercise_id' => 40, 'title' => 'Beginner Wrap-up', 'content_type' => 'badge', 'content' => '',  'extra' => 0, 'locale' => 'en'],

            //? Removed the enter key in the exercises since it's not possible to catch it

            // ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 17, 'title' => 'ز - 2', 'content_type' => 'letters', 'content' => '↵↵↵↵↵↵↵↵;;;;↵↵↵↵;;↵↵;;↵↵;↵;↵;↵;↵',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 17, 'title' => 'ز - 3', 'content_type' => 'letters', 'content' => 'zzzaaa↵↵;;zzaa↵;zzzaaa↵↵z↵↵zz↵↵zzaa↵↵;;↵;↵;zaza',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 17, 'title' => 'ز - 4', 'content_type' => 'letters', 'content' => 'azzzzzzazzzazzzazzzazzz;;;↵↵;;↵;↵↵;;↵;↵',  'extra' => "", 'locale' => 'en'],

            // ['lesson_id' => 9, 'order' => 1, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 1', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 2, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 2', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 3, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 3', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 4, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 4', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 5, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 5', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 6, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 6', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 7, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 7', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 8, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 8', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 9, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 9', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 10, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 10', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 11, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 11', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
            // ['lesson_id' => 9, 'order' => 12, 'exercise_id' => 32, 'title' => 'O, B, and A Keys - 12', 'content_type' => 'letters', 'content' => '',  'extra' => "", 'locale' => 'en'],
        ];

        foreach ($screens as $screenData) {
            Screen::create($screenData);
        }
    }
}
